Fix setting ScopeInfo property
Setting Scopeinfo property with previous settings: min, max, step, val:

ScopeInfoNP[FocalLength].fill("FOCAL_LENGTH", "Focal Length (mm)", "%.2f", 10, 10000, 100, 0);
ScopeInfoNP[Aperture].fill("APERTURE", "Aperture (mm)", "%.2f", 10, 3000, 100, 0);

resulted in error:

Error: Invalid range for Aperture (mm) (APERTURE). Valid range is from 10 to 3000. Requested value is 0
[DEBUG] Configuration successfully saved for SCOPE_INFO.
Error: Invalid range for Focal Length (mm) (FOCAL_LENGTH). Valid range is from 10 to 10000. Requested value is 0
[DEBUG] Configuration successfully saved for SCOPE_INFO.

because at least one property value is 0 by default however, min values are set
to 10mm, so the value cannot be set via the property settings. In addition the
step size is decreased to 1mm and enum values are in uppercase
letters. Moreover, the state of the property is IPS_OK only when the update is
successful, otherwise IPS_ALERT.